In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("enjoy - enjoy.csv")

In [4]:
df.head()

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

In [5]:
df.tail()

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sky         10 non-null     object
 1   AirTemp     10 non-null     object
 2   Humidity    10 non-null     object
 3   Wind        10 non-null     object
 4   Water       10 non-null     object
 5   Forecast    10 non-null     object
 6   EnjoySport  10 non-null     object
dtypes: object(7)
memory usage: 692.0+ bytes

## Find S

In [7]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [8]:
def find_s(X, y):
    hypothesis = None
    print("Initial hypothesis:", hypothesis)

    for i in range(len(X)):
        if y[i] == "acceptable":
            if hypothesis is None:
                hypothesis = X[i]
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = "?"

        print(f"\nAfter Training Example {i+1}:")
        print(hypothesis)

    return hypothesis

final_hypothesis = find_s(X, y)
print("\nFinal Hypothesis:")
print(final_hypothesis)

Initial hypothesis: None

After Training Example 1:
None

After Training Example 2:
None

After Training Example 3:
None

After Training Example 4:
None

After Training Example 5:
None

After Training Example 6:
None

After Training Example 7:
None

After Training Example 8:
None

After Training Example 9:
None

After Training Example 10:
None

Final Hypothesis:
None

## Candidate elimination

In [9]:
import copy

import copy

def candidate_elimination(concepts, target):

    specific = concepts[0].copy()
    general = [["?" for _ in range(len(specific))]]

    print("Initial S:", specific)
    print("Initial G:", general)

    for i, h in enumerate(concepts):

        if target[i] == "acceptable":

            for x in range(len(specific)):
                if h[x] != specific[x]:
                    specific[x] = "?"

            general = []
            for x in range(len(specific)):
                if specific[x] != "?":
                    general.append(
                        ["?" if j != x else specific[x] for j in range(len(specific))]
                    )

        print("\nExample", i + 1)
        print("S =", specific)
        print("G =", general)

    return specific, general


S, G = candidate_elimination(X, y)

print("\nFinal Specific Boundary:")
print(S)

print("\nFinal General Boundary:")
for g in G:
  print(g)

Initial S: ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Initial G: [['?', '?', '?', '?', '?', '?']]

Example 1
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 2
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 3
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 4
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 5
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 6
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 7
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 8
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 9
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 10
S = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Final Specific Boundary:
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

Final General Boundary:
['?', '?', '?', '?', '?', '?']